### PR TITLE
Add Rails 6 support

### PR DESCRIPTION
**Pull request by plicjo**

### CODE REVIEW

**Comment by plicjo** [comment]
@rwz This looks good to go.

**Comment by plicjo** [comment]
I will maintain a fork here: https://github.com/plicjo/adequate_exposure

**Comment by rwz** [comment]
Oh man, I completely missed this PR. It does look good to go. Will merge and release it if you reopen :)

**Comment by plicjo** [comment]
@rwz Oh wow. Ok, I reopened it just now!

**Comment by plicjo** [comment]
@rwz Important: I added the following commits today

https://github.com/rwz/adequate_exposure/pull/26/commits/ec644b68bc9e67fc3f80dd9de04a58902703746c
https://github.com/rwz/adequate_exposure/pull/26/commits/8e2ab18dc8551c976d65adfff5143090d772a34a
https://github.com/rwz/adequate_exposure/pull/26/commits/17b0b283d676bb81895ac3dc252da678dd967057

which added Ruby 2.7 support.

They're unrelated to this P/R, but they are small changes. Lemme know if you want me to do a separate P/R

**Comment by rwz** [comment]
LGTM

Will try to merge/ship later today after work.

Thanks for your patience :)

**Review by rwz — APPROVED** [review]

**Comment by rwz** [comment]
Released 0.6.0

**Comment by plicjo** [comment]
🔥

**Pull request merged**
